# Default values for .helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: e-chauffeur
image:
  repository: registry.gitlab.com/fabnum-minarm/e-chauffeur/api
  tag: stable
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
  REDIS: e-chauffeur-redis
  AMQP: rabbitmq.e-chauffeur
  MONGODB: e-chauffeur-mongodb
  TOKEN__DURATION: 3600
  TWILIO__SID: null
  TWILIO__TOKEN: null
  TWILIO__MESSAGING_SERVICE_SID: null
  MAIL__TRANSPORTER__HOST: null
  MAIL__TRANSPORTER__PORT: 587
  MAIL__TRANSPORTER__AUTH__USER: null
  MAIL__TRANSPORTER__AUTH__PASS: null
  MAIL__DEFAULT_FROM: null
  MAIL__FEEDBACK_MAIL: null
  MAIL__CONTACT_MAIL: null
  MAIL__HTML: "<p>:message</p>"
  MAIL__TEXT: ":message"
  MAIL__SUBJECT: ":gsbdd - :firstname :lastname (:email - :phone)."
  VAPID__PUBLIC_KEY: null
  VAPID__PRIVATE_KEY: null
  REDIRECT_TARGET: null
  USER_WEBSITE_URL: null
  WHITELIST_DOMAINS: null
  VERSION: null
imageCredentials:
  name: e-chauffeur-api
  registry: registry.gitlab.com
  username: user
  password: pass

service:
  type: ClusterIP
  port: 1337

ingress:
  enabled: true
  host: api.localhost
  issuer: self-signing

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 758Mi

nodeSelector: {}

tolerations: []

affinity: {}
