{{- if .Values.ingress.enabled -}}
{{- $fullName := include ".helm-chart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include ".helm-chart.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: traefik
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
