{{- $fullName := include ".helm-chart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include ".helm-chart.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Content-Range,Accept-Ranges"

spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.port }}
  tls:
    - secretName: {{$fullName}}-tls
      hosts:
      - {{ .Values.ingress.host | quote }}
